before_script:
  - pip install '.[test]'

test_job_py38:
  image: python:3.8
  script:
    - pytest
  stage: test

test_job_py37:
  image: python:3.7
  script:
    - pytest
  stage: test

test_job_py36:
  image: python:3.6
  script:
    - pytest
  stage: test
