#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['jeepney', 'jeepney.io']

package_data = \
{'': ['*']}

extras_require = \
{'test': ['pytest', 'pytest-trio', 'pytest-asyncio >=0.17', 'testpath', 'trio'],
 "test:python_version < '3.11'": ['async-timeout'],
 'trio': ['trio']}

setup(name='jeepney',
      version='0.9.0',
      description='Low-level, pure Python DBus protocol wrapper.',
      author=None,
      author_email='Thomas Kluyver <thomas@kluyver.me.uk>',
      url=None,
      packages=packages,
      package_data=package_data,
      extras_require=extras_require,
      python_requires='>=3.7',
     )
